model:
  name: resnetv2_101x1_bit.goog_in21k_ft_in1k
  pretrained: true
  custom_pretrained_init: null
  num_classes: 100
  dropout: 0.0
  resnetd: false
  attention: none
  se_mode: none
  se_reduction: 16
  drop_path_rate: 0.0
  param_limit_million: 100
